### ISSUE TITLE
Mustermann is not compatible with JRuby --enable=frozen-string-literal param

### ISSUE THREAD

**Issue by brometeo** [sinatra/mustermann#110]
It tries to modify a frozen String in the code line:

  mustermann-1.1.1/lib/mustermann/ast/node.rb:59

**Comment by brometeo** [comment]
Any news about this issue? Opinion? :(

**Comment by olleolleolle** [comment]
@brometeo Would you like to offer a PR?

**Comment by olleolleolle** [comment]
https://github.com/sinatra/mustermann/blob/master/mustermann/lib/mustermann/ast/node.rb#L111 This line defines a String which is not mutable, and we need it to be. +"" would make a mutable String, whereas "" (the existing code) is a frozen one.

**Comment by brometeo** [comment]
> @brometeo Would you like to offer a PR?

What is that? =:)

**Comment by namusyaka** [comment]
I'll take a look at this after switching our Ci into actions. Sorry for the late reply.

**Comment by michal-granec** [comment]
If it's ok with you @namusyaka I can handle the PR for this issue. WDYT?

**Comment by dentarg** [comment]
Go for it

**Comment by michal-granec** [comment]
@olleolleolle and @namusyaka PR is ready to be reviewed. Let me know if there is anything I should change, add or try out :wink:

**Comment by jkowens** [comment]
I merged @michal-granec's PR into mustermann master, but we'll need @namusyaka to cut a release to get the fix out.

**Comment by jkowens** [comment]
Released 1.1.2
