### ISSUE TITLE
Release gem(s), trying to use mustermann-grape

### ISSUE THREAD

**Issue by dblock** [sinatra/mustermann#52]
We're using [mustermann19](https://github.com/namusyaka/mustermann19) in https://github.com/ruby-grape. I'd like to move up to using mustermann-grape. What's the release plan here? Can I help?

**Comment by namusyaka** [comment]
Ah, yes I've forgotten the releasing.
I've just released `mustermann-grape` v0.4.0. Please check it out.
https://rubygems.org/gems/mustermann-grape

**Comment by dblock** [comment]
That was fast @namusyaka. Want to PR that into Grape too? Thanks!
