### ISSUE TITLE
Routers

### ISSUE THREAD

**Issue by andriytyurnikov** [sinatra/mustermann#59]
Hello guys, I see that routers were removed from gem itself - were they extracted into separate gem, or where could I find them?

**Comment by namusyaka** [comment]
@andriytyurnikov Routers were removed in [this commit](https://github.com/sinatra/mustermann/commit/387b1f8a6a76594a0025421e85f4f2c957e28b66).

**Comment by andriytyurnikov** [comment]
@namusyaka I seen that, so no plans to have those Routers in separate gem or something?

**Comment by namusyaka** [comment]
There are no plans to have routers at the moment.
However, [my router implementation](https://github.com/namusyaka/pendragon) may be helpful. It's implemented by using mustermann.

**Comment by andriytyurnikov** [comment]
@namusyaka, hope that would be good solution. Thank you!
