### ISSUE TITLE
Shorthand Error Syntax

### ISSUE THREAD

**Issue by kaiserprogrammer** [sinatra/mustermann#64]
Error class is not reserved in ruby, so it will be likely created and used.

Using Shorthand Error Syntax with or operator can lead to undefined classes.

Example:
```ruby
class Error; end
require "mustermann/sinatra"
```

mustermann-1.0.0/lib/mustermann/ast/translator.rb:98:in `<class:Translator>': uninitialized constant Mustermann::Error (NameError)

**Comment by namusyaka** [comment]
@kaiserprogrammer Could you confirm #66?

**Comment by kaiserprogrammer** [comment]
It Works!
