### ISSUE TITLE
Improve performance of `Mustermann.new`

### ISSUE THREAD

**Issue by stanhu** [sinatra/mustermann#69]
In GitLab, I've noticed `Mustermann.new` being a bottleneck in loading the Grape API:

![image](https://user-images.githubusercontent.com/963826/28485882-ab7b7990-6e31-11e7-9a0c-f9af4707e7ab.png)

I've reproduced it in a local example. On a VM, I see this taking 2.7 s:

```ruby
require 'mustermann'
data = File.readlines('/tmp/patterns.txt')
data.each { |x| Mustermann.new(x) }
```

[patterns.txt](https://github.com/sinatra/mustermann/files/1166963/patterns.txt)

Since in production these patterns never change, I'm wondering if we can pre-calculate these patterns, save this information to disk/memory, and reload them on demand.

**Comment by namusyaka** [comment]
@stanhu Thanks for your reporting. I'm going to take a look at the issue in a few days.

**Comment by zzak** [comment]
I'm not sure how Grape API works, but are you seeing this on boot or during an request?

**Comment by stanhu** [comment]
Just boot. Once this is loaded, everything is much faster, but when our Unicorn workers restart for some reason, we have to take this hit again.

**Comment by namusyaka** [comment]
To improve performance of every requests, grape compiles all patterns on boot.
I think that the essence of this problem has nothing to do with mustermann.
If the problem is critical, please open an issue at grape. https://github.com/ruby-grape/grape/
