### ISSUE TITLE
Expanding with unused empty array values

### ISSUE THREAD

**Issue by gerwitz** [sinatra/mustermann#88]
Passing in an unused value that is an empty array causes an entertaining failure.

`Expander.expand()` replaces the corresponding key with an empty array:
https://github.com/sinatra/mustermann/blob/34093954a77bbef159fa2a9fb3afc1c4b8354cda/mustermann/lib/mustermann/ast/expander.rb#L95

Then the mapping throws an error, which is "handled" by `Expander.error_for()` which attempts to sort the keys, naturally causing "ArgumentError - comparison of Symbol with Array"

**Comment by namusyaka** [comment]
@gerwitz Could you provide minimal example for reproducing the failure?

**Comment by gerwitz** [comment]
It's been a while and I hadn't discovered the `:ignore` flag then, but I think this is what I was talking about:
````
p = Mustermann.new(':one:two')
p.expand({one: 1, two: "2", three: [], four: "four"})
````
Note how removing the `:four` item from that Hash leads to a very different exception.

**Comment by namusyaka** [comment]
Thanks for the tips.
Definitely bug. I'll take a look soon.

**Comment by gerwitz** [comment]
👍 My tests get proper errors now.
